### ISSUE TITLE
README中的视频

### ISSUE THREAD

**Issue by zhongwenkun886** [Starrynightzyq/Drone_Vehicle_Flow_Detection#3]
您好，请问README中的演示视频的原始视频在哪里能找到，谢谢。

**Comment by Starrynightzyq** [comment]
你好，视频是我们实际项目测试用的，如果现在还需要我可以邮件发给你。

**Comment by Starrynightzyq** [comment]
> 您好，请问README中的演示视频的原始视频在哪里能找到，谢谢。

你好，视频是我们实际项目测试用的，如果现在还需要我可以邮件发给你。

**Comment by Starrynightzyq** [comment]
> 您好，请问README中的演示视频的原始视频在哪里能找到，谢谢。

你好，视频是我们实际项目测试用的，不太方便，不好意思啊。

**Comment by Starrynightzyq** [comment]
视频已上传
